// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzyqkvheufamvzodvalw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16eXFrdmhldWZhbXZ6b2R2YWx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyOTE1NjgsImV4cCI6MjA2NDg2NzU2OH0.Xrdzvu4m_M-CdXYOhqjcqJdPGJTsOQ5m4PbYnPWMORY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);